# Generated by Django 5.2 on 2025-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="responses",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
